---
- name: Check available collections
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check for community.vmware collection in collection paths
      ansible.builtin.find:
        paths:
          - /var/lib/awx/.ansible/collections/ansible_collections
          - /root/.ansible/collections/ansible_collections
          - /usr/share/ansible/collections/ansible_collections
        patterns: "vmware"
        file_type: directory
        recurse: yes
      register: collection_files

    - name: Debug collection paths
      ansible.builtin.debug:
        msg: "Found community.vmware at: {{ item.path }}"
      loop: "{{ collection_files.files }}"
      when: collection_files.matched > 0

    - name: Fail if collection is not found
      ansible.builtin.fail:
        msg: "community.vmware collection not found in any of the specified paths!"
      when: collection_files.matched == 0
