---
- name: Rename or revert an ESXi VM completely (files + config)
  hosts: 192.168.223.131
  gather_facts: false
  vars:
    vmx_dir: ""
    vm_id: ""

  tasks:
    - name: Get VM ID if registered
      shell: "sshpass -p '{{ esxi_password }}' ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} \"vim-cmd vmsvc/getallvms | grep -i '{{ old_vm_name }}'\""
      register: get_vmid
      changed_when: false

    - name: Set VM ID if found
      set_fact:
        vm_id: "{{ get_vmid.stdout.split()[0] }}"
      when: get_vmid.stdout != ""

    - name: Unregister VM if already registered
      shell: "sshpass -p '{{ esxi_password }}' ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/unregister {{ vm_id }}"
      when: vm_id != ""

    - name: Find VMX file path
      shell: "sshpass -p '{{ esxi_password }}' ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} find /vmfs/volumes/ -name '{{ old_vm_name }}.vmx'"
      register: vmx_path_result

    - name: Set VMX directory
      set_fact:
        vmx_dir: '/vmfs/volumes/{{ vmx_path_result.stdout.split("]")[0] | regex_replace("\\[|\\]", "") }}/{{ vmx_path_result.stdout.split("]")[1] | regex_replace("^ ", "") | dirname }}'

    - name: Optionally take a snapshot before changes
      shell: "sshpass -p '{{ esxi_password }}' ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} \"vim-cmd vmsvc/snapshot.create {{ vm_id }} prechange-{{ lookup('pipe','date +%Y%m%d-%H%M%S') }}\""
      when: take_snapshot | default(false) | bool and vm_id != ""

    - name: Rename all related files inside VM folder
      shell: >
        sshpass -p '{{ esxi_password }}' ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} '
        cd {{ vmx_dir }} && 
        for file in $(ls); do
          newname=$(echo "$file" | sed "s/{{ old_vm_name }}/{{ new_vm_name }}/g");
          mv "$file" "$newname";
        done'

    - name: Replace old VM name inside VMX config
      shell: >
        sshpass -p '{{ esxi_password }}' ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} \
        "sed -i 's/{{ old_vm_name }}/{{ new_vm_name }}/g' {{ vmx_dir }}/{{ new_vm_name }}.vmx"

    - name: Register renamed VM
      shell: >
        sshpass -p '{{ esxi_password }}' ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} \
        "vim-cmd solo/registervm {{ vmx_dir }}/{{ new_vm_name }}.vmx"

    - name: Print success message
      debug:
        msg: "VM '{{ old_vm_name }}' has been renamed and re-registered as '{{ new_vm_name }}'."

