---
- name: Safely rename an ESXi virtual machine
  hosts: localhost
  gather_facts: false
  vars:
    esxi_host: 192.168.223.131
    esxi_user: admin
    esxi_password: redhat
    old_vm_name: linux-testmac_1
    new_vm_name: linux-testmac_1_renamed
    datastore_name: datastore1
    vm_folder: "/vmfs/volumes/{{ datastore_name }}/{{ new_vm_name }}"

  tasks:

    - name: Get VMID of the old VM
      shell: |
        sshpass -p {{ esxi_password }} ssh -o StrictHostKeyChecking=no {{ esxi_user }}@{{ esxi_host }} "vim-cmd vmsvc/getallvms | grep {{ old_vm_name }} | awk '{print $1}'"
      register: vmid_result

    - name: Set VMID fact
      set_fact:
        vm_id: "{{ vmid_result.stdout }}"

    - name: Power off the VM
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} "vim-cmd vmsvc/power.off {{ vm_id }}"
      when: vm_id != ""
      ignore_errors: true

    - name: Wait for VM to power off
      pause:
        seconds: 10

    - name: Unregister the VM from inventory
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} "vim-cmd vmsvc/unregister {{ vm_id }}"
      when: vm_id != ""
      ignore_errors: true

    - name: Rename VM folder
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} \
        "mv /vmfs/volumes/{{ datastore_name }}/{{ old_vm_name }} {{ vm_folder }}"

    - name: Rename all internal files inside the folder
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} \
        "cd {{ vm_folder }} && for f in *{{ old_vm_name }}*; do newf=$(echo $f | sed 's/{{ old_vm_name }}/{{ new_vm_name }}/g'); mv \"$f\" \"$newf\"; done"

    - name: Update VMX file contents to reflect new disk names
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} \
        "sed -i 's/{{ old_vm_name }}/{{ new_vm_name }}/g' {{ vm_folder }}/{{ new_vm_name }}.vmx"

    - name: Register the renamed VM
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} \
        "vim-cmd solo/registervm {{ vm_folder }}/{{ new_vm_name }}.vmx"

    - name: Wait before power on
      pause:
        seconds: 5

    - name: Get new VM ID
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} \
        "vim-cmd vmsvc/getallvms | grep {{ new_vm_name }} | awk '{print $1}'"
      register: new_vmid_result

    - name: Set new VMID
      set_fact:
        new_vm_id: "{{ new_vmid_result.stdout }}"

    - name: Power on the newly renamed VM
      shell: |
        sshpass -p {{ esxi_password }} ssh {{ esxi_user }}@{{ esxi_host }} \
        "vim-cmd vmsvc/power.on {{ new_vm_id }}"

