---
- name: Rename or revert an ESXi VM safely
  hosts: 192.168.223.131
  gather_facts: no
  vars:
    old_vm_name: "{{ old_vm_name | default('linux-testmachine') }}"
    new_vm_name: "{{ new_vm_name | default('linux-renamed') }}"
    power_on: "{{ power_on | default('true') }}"
    snapshot_before: "{{ snapshot_before | default('false') }}"
    mode: "{{ mode | default('rename') }}"
  tasks:

    - name: Get all VMs
      shell: vim-cmd vmsvc/getallvms
      register: vm_list

    - name: Fail if VM list is empty or malformed
      fail:
        msg: "Failed to get VMs or no VMs found on the ESXi host"
      when: vm_list.stdout_lines | length <= 1

    - name: Display current VM count
      debug:
        msg: "There are {{ vm_list.stdout_lines | length - 1 }} VMs on the host."

    - name: Extract line for old VM
      set_fact:
        old_vm_line: "{{ item }}"
      loop: "{{ vm_list.stdout_lines[1:] }}"
      when: "'{{ old_vm_name }}' in item"
      register: old_vm_line_check

    - name: Fail if old VM is not found
      fail:
        msg: "VM named '{{ old_vm_name }}' not found."
      when: old_vm_line_check.results | selectattr('ansible_facts.old_vm_line', 'defined') | list | length == 0

    - name: Set old VM details
      set_fact:
        vmid: "{{ (old_vm_line_check.results | selectattr('ansible_facts.old_vm_line', 'defined') | map(attribute='ansible_facts.old_vm_line') | list).0.split()[0] }}"
        current_vm_name: "{{ old_vm_name if mode == 'rename' else new_vm_name }}"
        target_vm_name: "{{ new_vm_name if mode == 'rename' else old_vm_name }}"
        datastore_path: "{{ (old_vm_line_check.results | selectattr('ansible_facts.old_vm_line', 'defined') | map(attribute='ansible_facts.old_vm_line') | list).0.split()[2] }}"

    - name: Take snapshot before rename (if enabled)
      shell: "vim-cmd vmsvc/snapshot.create {{ vmid }} pre_rename_snapshot 'Snapshot before renaming VM'"
      when: snapshot_before | bool

    - name: Power off VM before renaming/unregistering
      shell: "vim-cmd vmsvc/power.off {{ vmid }}"
      ignore_errors: yes

    - name: Rename or revert VM files (folder, VMDK, VMX)
      shell: |
        SRC_DIR="/vmfs/volumes/{{ datastore_path | regex_replace('[\\[\\]]', '') }}/{{ current_vm_name }}"
        DST_DIR="/vmfs/volumes/{{ datastore_path | regex_replace('[\\[\\]]', '') }}/{{ target_vm_name }}"

        if [ ! -d "$SRC_DIR" ]; then
          echo "Source directory $SRC_DIR doesn't exist, assuming already renamed. Skipping."
          exit 0
        fi

        mv "$SRC_DIR" "$DST_DIR"

        for f in "$DST_DIR"/*{{ current_vm_name }}*; do
          mv "$f" "${f//${current_vm_name}/${target_vm_name}}"
        done

        sed -i "s/${current_vm_name}/${target_vm_name}/g" "$DST_DIR/${target_vm_name}.vmx"
      register: rename_result
      ignore_errors: yes

    - name: Unregister original VM
      shell: "vim-cmd vmsvc/unregister {{ vmid }}"
      register: unregister_result
      failed_when: unregister_result.rc != 0 and 'Powered on' not in unregister_result.stderr

    - name: Re-register renamed VM
      shell: |
        VMX_PATH="{{ datastore_path }}/{{ target_vm_name }}/{{ target_vm_name }}.vmx"
        vim-cmd solo/registervm "$VMX_PATH"
      when: unregister_result is succeeded or 'Powered on' in unregister_result.stderr

    - name: Power on VM if requested
      shell: vim-cmd vmsvc/power.on $(vim-cmd vmsvc/getallvms | grep "{{ target_vm_name }}" | awk '{print $1}')
      when: power_on | bool

    - name: Final validation output
      shell: vim-cmd vmsvc/getallvms | grep "{{ target_vm_name }}"
      register: final_check

    - name: Show final registered VM line
      debug:
        var: final_check.stdout_lines

