---
- name: Rename or revert an ESXi VM safely
  hosts: 192.168.223.131
  gather_facts: false
  become: yes
  vars:
    power_on: true  # Set to true to power on VM after rename
  tasks:

    - name: List all VMs on ESXi host
      shell: vim-cmd vmsvc/getallvms
      register: getallvms_output

    - name: Count existing VMs on host
      set_fact:
        vm_count: "{{ getallvms_output.stdout_lines | length - 1 }}"

    - name: Display current VM count
      debug:
        msg: "There are {{ vm_count }} VMs on the host."

    - name: Fail if old and new names are identical
      fail:
        msg: "Old and new VM names are identical ({{ old_vm_name }}); nothing to do."
      when: old_vm_name == new_vm_name

    - name: Prevent duplicate renaming if new name includes old name
      fail:
        msg: "The new VM name '{{ new_vm_name }}' appears to include the old VM name '{{ old_vm_name }}'. Duplicate renaming is not allowed."
      when: new_vm_name.endswith(old_vm_name)

    - name: Check for existing VM with new name
      fail:
        msg: "A VM with the name '{{ new_vm_name }}' already exists on the host. Aborting rename."
      when: (" " + new_vm_name + " ") in getallvms_output.stdout

    - name: Search for line containing old VM name
      set_fact:
        old_vm_line: >-
          {{ getallvms_output.stdout_lines
             | select('match', '^\\s*\\d+\\s+' + old_vm_name + '\\s')
             | list | first | default('') }}

    - name: Fail if old VM is not found
      fail:
        msg: "VM '{{ old_vm_name }}' not found. Nothing to rename."
      when: old_vm_line == ''

    - name: Extract old VM ID from matched line
      set_fact:
        old_vm_id: "{{ old_vm_line.split()[0] }}"

    - name: Check the power state of the old VM
      shell: vim-cmd vmsvc/power.getstate {{ old_vm_id }}
      register: power_state

    - name: Power off the old VM if it is powered on
      shell: vim-cmd vmsvc/power.off {{ old_vm_id }}
      when: "'Powered on' in power_state.stdout"

    - name: Unregister the old VM from ESXi host inventory
      shell: vim-cmd vmsvc/unregister {{ old_vm_id }}

    - name: Check if the old VM folder exists on the datastore
      stat:
        path: /vmfs/volumes/datastore1/{{ old_vm_name }}
      register: old_folder

    - name: Check if the new VM folder already exists on the datastore
      stat:
        path: /vmfs/volumes/datastore1/{{ new_vm_name }}
      register: new_folder

    - name: Fail if target VM folder already exists (avoid conflict)
      fail:
        msg: "Target VM folder '/vmfs/volumes/datastore1/{{ new_vm_name }}' already exists. Aborting."
      when: new_folder.stat.exists

    - name: Rename VM folder on datastore
      shell: mv /vmfs/volumes/datastore1/{{ old_vm_name }} /vmfs/volumes/datastore1/{{ new_vm_name }}
      when: old_folder.stat.exists and not new_folder.stat.exists

    - name: Rename VM files inside the folder to new name
      shell: |
        cd /vmfs/volumes/datastore1/{{ new_vm_name }}
        for f in *; do
          if [[ "$f" == *"{{ old_vm_name }}"* ]]; then
            mv "$f" "${f/{{ old_vm_name }}/{{ new_vm_name }}}"
          fi
        done
      args:
        executable: /bin/bash
      when: old_folder.stat.exists and not new_folder.stat.exists

    - name: Update VMX file displayName and references to new name
      replace:
        path: /vmfs/volumes/datastore1/{{ new_vm_name }}/{{ new_vm_name }}.vmx
        regexp: "{{ old_vm_name }}"
        replace: "{{ new_vm_name }}"
      when: old_folder.stat.exists and not new_folder.stat.exists

    - name: Check if VMSD (snapshot descriptor) exists
      stat:
        path: /vmfs/volumes/datastore1/{{ new_vm_name }}/{{ new_vm_name }}.vmsd
      register: vmsd_file

    - name: Update VMSD references to new name
      replace:
        path: /vmfs/volumes/datastore1/{{ new_vm_name }}/{{ new_vm_name }}.vmsd
        regexp: "{{ old_vm_name }}"
        replace: "{{ new_vm_name }}"
      when: vmsd_file.stat.exists and old_folder.stat.exists and not new_folder.stat.exists

    - name: Register the VM with the new name in ESXi
      shell: vim-cmd solo/registervm /vmfs/volumes/datastore1/{{ new_vm_name }}/{{ new_vm_name }}.vmx
      register: register_vm

    - name: Get the new VM ID after registration
      shell: vim-cmd vmsvc/getallvms | grep " {{ new_vm_name }} " | awk '{print $1}'
      register: new_vm_id_search

    - name: Set fact for new VM ID
      set_fact:
        new_vm_id: "{{ new_vm_id_search.stdout }}"

    - name: Fail if new VM registration failed
      fail:
        msg: "Registration of VM '{{ new_vm_name }}' failed - new VM not found."
      when: new_vm_id == ""

    - name: Create a snapshot of the renamed VM for backup
      shell: 'vim-cmd vmsvc/snapshot.create {{ new_vm_id }} "{{ new_vm_name }}_snapshot" "Snapshot created after renaming VM" 0 0'

    - name: Power on the new VM if requested
      shell: vim-cmd vmsvc/power.on {{ new_vm_id }}
      when: power_on | bool

    - name: List all VMs on ESXi host after rename
      shell: vim-cmd vmsvc/getallvms
      register: final_vms

    - name: Display final VM list
      debug:
        msg: "{{ final_vms.stdout }}"

