# rename_vm_esxi.yml
---
- name: Manage ESXi Virtual Machine
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
  vars:
    esxi_host: "192.168.223.131"
    vm_name: "linux-testmac"
    validate_certs: false
    datacenter: "ha-datacenter"
    esxi_username: "root"          # Replace with your credentials
    esxi_password: "yourpassword"  # Replace with your credentials
    folder: "/{{ datacenter }}/vm" # Standard folder path for standalone ESXi

  tasks:
    # ========== CONNECTION VERIFICATION ==========
    - name: Verify ESXi connection
      vmware_vm_info:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
      register: connection_test
      tags: always

    - name: Fail if connection failed
      ansible.builtin.fail:
        msg: "Failed to connect to ESXi host: {{ connection_test.msg | default('Unknown error') }}"
      when: connection_test.failed | default(false)
      tags: always

    # ========== VM INFORMATION GATHERING ==========
    - name: Get detailed VM info (with required datacenter)
      community.vmware.vmware_guest_info:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
      register: vm_info
      tags: info

    # ========== POWER MANAGEMENT ==========
    - name: Power off VM if running (with proper parameters)
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ vm_name }}"
        state: powered-off
        state_change_timeout: 300
      when: vm_info.instance.power_state == 'poweredOn'
      register: power_action
      tags: power

    # ========== VM RENAMING ==========
    - name: Rename VM (using correct module parameters)
      community.vmware.vmware_guest:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ vm_name }}"
        uuid: "{{ vm_info.instance.uuid }}"
        hardware:
          name: "new-vm-name"  # This is how renaming works in vmware_guest
      register: rename_result
      tags: rename

    # ========== POST-RENAME OPERATIONS ==========
    - name: Power on VM if it was powered off
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "new-vm-name"
        state: powered-on
        state_change_timeout: 300
      when:
        - power_action is defined
        - power_action.changed
      tags: power
