---
- name: Search for a VM in ESXi with dynamic inputs
  hosts: localhost
  gather_facts: no
  vars:
    esxi_hostname: "192.168.223.131"
    esxi_username: "{{ ansible_user | default('root') }}"
    esxi_password: "{{ ansible_password | default('PotterHead@123') }}"
    vm_name: "{{ vm_name | default('test-vm') }}"
  tasks:
    - name: Search for the specified VM in ESXi
      community.vmware.vmware_guest_find:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
      register: vm_info

    - name: Debug VM info
      ansible.builtin.debug:
        var: vm_info
